#!/usr/bin/env php
<?php

require 'vendor/autoload.php';

use Lagoon\LagoonClient;

// The container exposes port 3000 on the host by default.
$endpoint = "http://localhost:3000/graphql";

// The development container uses this token for everyone.
$token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiYWRtaW4iLCJpc3MiOiJhcGktZGF0YS13YXRjaGVyLXB1c2hlciIsImF1ZCI6ImFwaS5kZXYiLCJzdWIiOiJhcGktZGF0YS13YXRjaGVyLXB1c2hlciJ9.GiSJpvNXF2Yj9IXVCsp7KrxVp8N2gcp7-6qpyNOakVw";

try {
  $client = new LagoonClient($endpoint, $token);
  $response = $client->project()->all()->execute();

  if ($response->hasErrors()) {
    throw new \Exception("There were errors returned from the GraphQL API: " . implode(PHP_EOL, $response->errors()));
  }
  else {
    $projects = $response->all();
    print "Projects Found: " . count($projects);
  }
} catch (\Exception $e) {
   print "ERROR: " . $e->getMessage();
   exit(1);
}
