#!/usr/bin/env bash
set -e
THIS_FILE_PATH="$( cd "$(dirname $(readlink -f "$0"))" ; pwd -P )"
cd $THIS_FILE_PATH

docker-compose up -d

# Connects the Lando container group to the API container.
docker network connect demolagoonsh_default lagoon_api_1 \
  || echo "Docker network connect failed, but that's ok. Moving on."
