#!/usr/bin/env bash
set -ex

CI_BUILD_TAG=php_sdk

cd tests
docker-compose up -d

# Connects the Lando container group to the API container.
docker network connect demolagoonsh_default lagoon_api_1 \
  || echo "Docker network connect failed, but that's ok. Moving on."
